[project]
name = 'Tokenized-Decentralized-Structured-Products'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.component-tracking]
path = 'contracts/component-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.investor-protection]
path = 'contracts/investor-protection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
